name: Sync LeetCode Submissions

on:
  workflow_dispatch: # Allows you to run it manually at any time
  schedule:
    - cron: '0*/12 * * *' # Automatically runs every night at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
